# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      
    working_directory: /go/src/github.com/ddddddO/tryCircleCI
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: 
          name: Run test
          command: |
            cd ./cmd/ci-test/
            go mod download
            go test -v

      - run:
          name: Output coverage
          command: |
            cd ./cmd/ci-test/
            go test -coverprofile=cover.out
            go tool cover -html=cover.out -o cover.html
